-- Complete Book Seeding Script for ResumeAI
-- This script inserts 100+ popular books with real summaries and key insights
-- Matches exact database schema: books table and summaries table

-- First, clear existing data (optional - uncomment if you want to start fresh)
-- DELETE FROM public.summaries;
-- DELETE FROM public.books;

-- Insert Books (only using existing columns)
-- Let database auto-generate UUIDs for id column
INSERT INTO public.books (title, author, cover_url, category, language, source_type, full_text_url, read_time_mins, created_at) VALUES
('Atomic Habits', 'James Clear', 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg', 'Productivity', 'en', 'book', NULL, 15, NOW()),
('The Lean Startup', 'Eric Ries', 'https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg', 'Business', 'en', 'book', NULL, 18, NOW()),
('Zero to One', 'Peter Thiel', 'https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg', 'Business', 'en', 'book', NULL, 16, NOW()),
('Good to Great', 'Jim Collins', 'https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg', 'Business', 'en', 'book', NULL, 17, NOW()),
('Start With Why', 'Simon Sinek', 'https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg', 'Leadership', 'en', 'book', NULL, 14, NOW()),
('The 4-Hour Work Week', 'Tim Ferriss', 'https://covers.openlibrary.org/b/isbn/9780307353139-L.jpg', 'Productivity', 'en', 'book', NULL, 19, NOW()),
('The Innovator''s Dilemma', 'Clayton Christensen', 'https://covers.openlibrary.org/b/isbn/9781633691780-L.jpg', 'Business', 'en', 'book', NULL, 18, NOW()),
('Blue Ocean Strategy', 'W. Chan Kim', 'https://covers.openlibrary.org/b/isbn/9781591396192-L.jpg', 'Business', 'en', 'book', NULL, 16, NOW()),
('The E-Myth Revisited', 'Michael Gerber', 'https://covers.openlibrary.org/b/isbn/9780887307287-L.jpg', 'Business', 'en', 'book', NULL, 17, NOW()),
('Scaling Up', 'Verne Harnish', 'https://covers.openlibrary.org/b/isbn/9781942958303-L.jpg', 'Business', 'en', 'book', NULL, 18, NOW()),
('The Hard Thing About Hard Things', 'Ben Horowitz', 'https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg', 'Business', 'en', 'book', NULL, 16, NOW()),
('Daring Greatly', 'Brené Brown', 'https://covers.openlibrary.org/b/isbn/9781592407330-L.jpg', 'Leadership', 'en', 'book', NULL, 15, NOW()),
('Extreme Ownership', 'Jocko Willink', 'https://covers.openlibrary.org/b/isbn/9781250185563-L.jpg', 'Leadership', 'en', 'book', NULL, 14, NOW()),
('Leaders Eat Last', 'Simon Sinek', 'https://covers.openlibrary.org/b/isbn/9781591848011-L.jpg', 'Leadership', 'en', 'book', NULL, 16, NOW()),
('The 7 Habits of Highly Effective People', 'Stephen Covey', 'https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg', 'Productivity', 'en', 'book', NULL, 18, NOW()),
('Deep Work', 'Cal Newport', 'https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg', 'Productivity', 'en', 'book', NULL, 15, NOW()),
('Essentialism', 'Greg McKeown', 'https://covers.openlibrary.org/b/isbn/9780804137386-L.jpg', 'Productivity', 'en', 'book', NULL, 14, NOW()),
('Getting Things Done', 'David Allen', 'https://covers.openlibrary.org/b/isbn/9780142000281-L.jpg', 'Productivity', 'en', 'book', NULL, 17, NOW()),
('The ONE Thing', 'Gary Keller', 'https://covers.openlibrary.org/b/isbn/9781885167774-L.jpg', 'Productivity', 'en', 'book', NULL, 15, NOW()),
('Indistractable', 'Nir Eyal', 'https://covers.openlibrary.org/b/isbn/9780525536450-L.jpg', 'Productivity', 'en', 'book', NULL, 14, NOW()),

-- Psychology & Self-Help Books
('Thinking, Fast and Slow', 'Daniel Kahneman', 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg', 'Psychology', 'en', 'book', NULL, 20, NOW()),
('Mindset', 'Carol Dweck', 'https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg', 'Psychology', 'en', 'book', NULL, 16, NOW()),
('Grit', 'Angela Duckworth', 'https://covers.openlibrary.org/b/isbn/9781501111109-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('Emotional Intelligence', 'Daniel Goleman', 'https://covers.openlibrary.org/b/isbn/9780553383713-L.jpg', 'Psychology', 'en', 'book', NULL, 17, NOW()),
('Flow', 'Mihaly Csikszentmihalyi', 'https://covers.openlibrary.org/b/isbn/9780061339202-L.jpg', 'Psychology', 'en', 'book', NULL, 18, NOW()),
('The Power of Now', 'Eckhart Tolle', 'https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg', 'Self-Help', 'en', 'book', NULL, 16, NOW()),
('Man''s Search for Meaning', 'Viktor Frankl', 'https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg', 'Psychology', 'en', 'book', NULL, 14, NOW()),
('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg', 'Self-Help', 'en', 'book', NULL, 15, NOW()),
('The Gifts of Imperfection', 'Brené Brown', 'https://covers.openlibrary.org/b/isbn/9781592858491-L.jpg', 'Self-Help', 'en', 'book', NULL, 14, NOW()),
('Untamed', 'Glennon Doyle', 'https://covers.openlibrary.org/b/isbn/9781984859729-L.jpg', 'Self-Help', 'en', 'book', NULL, 16, NOW()),
('Educated', 'Tara Westover', 'https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg', 'Self-Help', 'en', 'book', NULL, 18, NOW()),
('Becoming', 'Michelle Obama', 'https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg', 'Self-Help', 'en', 'book', NULL, 19, NOW()),
('You Are a Badass', 'Jen Sincero', 'https://covers.openlibrary.org/b/isbn/9780762447695-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('The Magic of Thinking Big', 'David Schwartz', 'https://covers.openlibrary.org/b/isbn/9780671646783-L.jpg', 'Self-Help', 'en', 'book', NULL, 16, NOW()),
('How to Win Friends and Influence People', 'Dale Carnegie', 'https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg', 'Self-Help', 'en', 'book', NULL, 17, NOW()),
('Think and Grow Rich', 'Napoleon Hill', 'https://covers.openlibrary.org/b/isbn/9780449214923-L.jpg', 'Self-Help', 'en', 'book', NULL, 16, NOW()),

-- Finance Books
('Rich Dad Poor Dad', 'Robert Kiyosaki', 'https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg', 'Finance', 'en', 'book', NULL, 15, NOW()),
('The Intelligent Investor', 'Benjamin Graham', 'https://covers.openlibrary.org/b/isbn/9780060555665-L.jpg', 'Finance', 'en', 'book', NULL, 20, NOW()),
('The Little Book of Common Sense Investing', 'John Bogle', 'https://covers.openlibrary.org/b/isbn/9781119404507-L.jpg', 'Finance', 'en', 'book', NULL, 14, NOW()),
('A Random Walk Down Wall Street', 'Burton Malkiel', 'https://covers.openlibrary.org/b/isbn/9780393358384-L.jpg', 'Finance', 'en', 'book', NULL, 18, NOW()),
('The Psychology of Money', 'Morgan Housel', 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg', 'Finance', 'en', 'book', NULL, 15, NOW()),
('I Will Teach You to Be Rich', 'Ramit Sethi', 'https://covers.openlibrary.org/b/isbn/9781523505746-L.jpg', 'Finance', 'en', 'book', NULL, 16, NOW()),
('The Simple Path to Wealth', 'JL Collins', 'https://covers.openlibrary.org/b/isbn/9781533667922-L.jpg', 'Finance', 'en', 'book', NULL, 14, NOW()),
('Your Money or Your Life', 'Vicki Robin', 'https://covers.openlibrary.org/b/isbn/9780143129290-L.jpg', 'Finance', 'en', 'book', NULL, 17, NOW()),
('The Millionaire Next Door', 'Thomas Stanley', 'https://covers.openlibrary.org/b/isbn/9781589795474-L.jpg', 'Finance', 'en', 'book', NULL, 16, NOW()),
('The Total Money Makeover', 'Dave Ramsey', 'https://covers.openlibrary.org/b/isbn/9781592555764-L.jpg', 'Finance', 'en', 'book', NULL, 15, NOW()),

-- Science Books
('Sapiens', 'Yuval Noah Harari', 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg', 'Science', 'en', 'book', NULL, 19, NOW()),
('A Brief History of Time', 'Stephen Hawking', 'https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg', 'Science', 'en', 'book', NULL, 17, NOW()),
('The Selfish Gene', 'Richard Dawkins', 'https://covers.openlibrary.org/b/isbn/9780198575191-L.jpg', 'Science', 'en', 'book', NULL, 18, NOW()),
('Cosmos', 'Carl Sagan', 'https://covers.openlibrary.org/b/isbn/9780345331359-L.jpg', 'Science', 'en', 'book', NULL, 18, NOW()),
('The Origin of Species', 'Charles Darwin', 'https://covers.openlibrary.org/b/isbn/9780140432054-L.jpg', 'Science', 'en', 'book', NULL, 20, NOW()),
('A Short History of Nearly Everything', 'Bill Bryson', 'https://covers.openlibrary.org/b/isbn/9780767908184-L.jpg', 'Science', 'en', 'book', NULL, 19, NOW()),
('The Elegant Universe', 'Brian Greene', 'https://covers.openlibrary.org/b/isbn/9780375708114-L.jpg', 'Science', 'en', 'book', NULL, 18, NOW()),
('The Gene', 'Siddhartha Mukherjee', 'https://covers.openlibrary.org/b/isbn/9781476733523-L.jpg', 'Science', 'en', 'book', NULL, 19, NOW()),
('The Body', 'Bill Bryson', 'https://covers.openlibrary.org/b/isbn/9780385539302-L.jpg', 'Science', 'en', 'book', NULL, 18, NOW()),
('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 'https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg', 'Science', 'en', 'book', NULL, 14, NOW()),

-- Philosophy Books
('Meditations', 'Marcus Aurelius', 'https://covers.openlibrary.org/b/isbn/9780812968255-L.jpg', 'Philosophy', 'en', 'book', NULL, 15, NOW()),
('The Art of War', 'Sun Tzu', 'https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg', 'Philosophy', 'en', 'book', NULL, 12, NOW()),
('The Republic', 'Plato', 'https://covers.openlibrary.org/b/isbn/9780140455113-L.jpg', 'Philosophy', 'en', 'book', NULL, 18, NOW()),
('Nicomachean Ethics', 'Aristotle', 'https://covers.openlibrary.org/b/isbn/9780872204645-L.jpg', 'Philosophy', 'en', 'book', NULL, 17, NOW()),
('Beyond Good and Evil', 'Friedrich Nietzsche', 'https://covers.openlibrary.org/b/isbn/9780679724650-L.jpg', 'Philosophy', 'en', 'book', NULL, 16, NOW()),
('The Stranger', 'Albert Camus', 'https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg', 'Philosophy', 'en', 'book', NULL, 15, NOW()),
('Existentialism is a Humanism', 'Jean-Paul Sartre', 'https://covers.openlibrary.org/b/isbn/9780300084559-L.jpg', 'Philosophy', 'en', 'book', NULL, 13, NOW()),
('The Consolations of Philosophy', 'Alain de Botton', 'https://covers.openlibrary.org/b/isbn/9780679779179-L.jpg', 'Philosophy', 'en', 'book', NULL, 15, NOW()),
('How to Live', 'Sarah Bakewell', 'https://covers.openlibrary.org/b/isbn/9781594203355-L.jpg', 'Philosophy', 'en', 'book', NULL, 16, NOW()),
('When Breath Becomes Air', 'Paul Kalanithi', 'https://covers.openlibrary.org/b/isbn/9780812988406-L.jpg', 'Philosophy', 'en', 'book', NULL, 14, NOW()),

-- Additional Popular Books
('Outliers', 'Malcolm Gladwell', 'https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg', 'Psychology', 'en', 'book', NULL, 16, NOW()),
('The Tipping Point', 'Malcolm Gladwell', 'https://covers.openlibrary.org/b/isbn/9780316346627-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('Blink', 'Malcolm Gladwell', 'https://covers.openlibrary.org/b/isbn/9780316010665-L.jpg', 'Psychology', 'en', 'book', NULL, 14, NOW()),
('David and Goliath', 'Malcolm Gladwell', 'https://covers.openlibrary.org/b/isbn/9780316204361-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('The Alchemist', 'Paulo Coelho', 'https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('The Five Love Languages', 'Gary Chapman', 'https://covers.openlibrary.org/b/isbn/9780802473156-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('The Purpose Driven Life', 'Rick Warren', 'https://covers.openlibrary.org/b/isbn/9780310267305-L.jpg', 'Self-Help', 'en', 'book', NULL, 16, NOW()),
('The Four Agreements', 'Don Miguel Ruiz', 'https://covers.openlibrary.org/b/isbn/9781878424310-L.jpg', 'Self-Help', 'en', 'book', NULL, 11, NOW()),
('The Secret', 'Rhonda Byrne', 'https://covers.openlibrary.org/b/isbn/9781582701707-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('The Power of Habit', 'Charles Duhigg', 'https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('Quiet', 'Susan Cain', 'https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg', 'Psychology', 'en', 'book', NULL, 16, NOW()),
('Predictably Irrational', 'Dan Ariely', 'https://covers.openlibrary.org/b/isbn/9780061353239-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('Influence', 'Robert Cialdini', 'https://covers.openlibrary.org/b/isbn/9780061241895-L.jpg', 'Psychology', 'en', 'book', NULL, 16, NOW()),
('The Willpower Instinct', 'Kelly McGonigal', 'https://covers.openlibrary.org/b/isbn/9781583334386-L.jpg', 'Psychology', 'en', 'book', NULL, 14, NOW()),
('Stumbling on Happiness', 'Daniel Gilbert', 'https://covers.openlibrary.org/b/isbn/9780307477107-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('Switch', 'Chip Heath', 'https://covers.openlibrary.org/b/isbn/9780385528757-L.jpg', 'Psychology', 'en', 'book', NULL, 14, NOW()),
('Nudge', 'Richard Thaler', 'https://covers.openlibrary.org/b/isbn/9780300122237-L.jpg', 'Psychology', 'en', 'book', NULL, 15, NOW()),
('The Paradox of Choice', 'Barry Schwartz', 'https://covers.openlibrary.org/b/isbn/9780062447420-L.jpg', 'Psychology', 'en', 'book', NULL, 13, NOW()),
('Drive', 'Daniel Pink', 'https://covers.openlibrary.org/b/isbn/9781594484803-L.jpg', 'Psychology', 'en', 'book', NULL, 14, NOW()),
('The War of Art', 'Steven Pressfield', 'https://covers.openlibrary.org/b/isbn/9781936891026-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('Big Magic', 'Elizabeth Gilbert', 'https://covers.openlibrary.org/b/isbn/9781594634726-L.jpg', 'Self-Help', 'en', 'book', NULL, 14, NOW()),
('Rising Strong', 'Brené Brown', 'https://covers.openlibrary.org/b/isbn/9780812995273-L.jpg', 'Self-Help', 'en', 'book', NULL, 15, NOW()),
('Braving the Wilderness', 'Brené Brown', 'https://covers.openlibrary.org/b/isbn/9780812995761-L.jpg', 'Self-Help', 'en', 'book', NULL, 14, NOW()),
('Dare to Lead', 'Brené Brown', 'https://covers.openlibrary.org/b/isbn/9780399592522-L.jpg', 'Leadership', 'en', 'book', NULL, 16, NOW()),
('The Compound Effect', 'Darren Hardy', 'https://covers.openlibrary.org/b/isbn/9780735213793-L.jpg', 'Productivity', 'en', 'book', NULL, 13, NOW()),
('The Miracle Morning', 'Hal Elrod', 'https://covers.openlibrary.org/b/isbn/9780979019732-L.jpg', 'Productivity', 'en', 'book', NULL, 13, NOW()),
('High Performance Habits', 'Brendon Burchard', 'https://covers.openlibrary.org/b/isbn/9781401952313-L.jpg', 'Productivity', 'en', 'book', NULL, 15, NOW()),
('The 5 AM Club', 'Robin Sharma', 'https://covers.openlibrary.org/b/isbn/9781443450066-L.jpg', 'Productivity', 'en', 'book', NULL, 14, NOW()),
('Finish', 'Jon Acuff', 'https://covers.openlibrary.org/b/isbn/9780718078731-L.jpg', 'Productivity', 'en', 'book', NULL, 12, NOW()),
('The 80/20 Principle', 'Richard Koch', 'https://covers.openlibrary.org/b/isbn/9781857882005-L.jpg', 'Productivity', 'en', 'book', NULL, 14, NOW()),
('The Power of Full Engagement', 'Jim Loehr', 'https://covers.openlibrary.org/b/isbn/9780743226752-L.jpg', 'Productivity', 'en', 'book', NULL, 14, NOW()),
('The Upside of Stress', 'Kelly McGonigal', 'https://covers.openlibrary.org/b/isbn/9781583335284-L.jpg', 'Psychology', 'en', 'book', NULL, 13, NOW()),
('The Happiness Project', 'Gretchen Rubin', 'https://covers.openlibrary.org/b/isbn/9780061583260-L.jpg', 'Self-Help', 'en', 'book', NULL, 14, NOW()),
('Better Than Before', 'Gretchen Rubin', 'https://covers.openlibrary.org/b/isbn/9780385348614-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('The Four Tendencies', 'Gretchen Rubin', 'https://covers.openlibrary.org/b/isbn/9780451489284-L.jpg', 'Psychology', 'en', 'book', NULL, 13, NOW()),
('Outer Order, Inner Calm', 'Gretchen Rubin', 'https://covers.openlibrary.org/b/isbn/9781984854719-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('The Life-Changing Magic of Tidying Up', 'Marie Kondo', 'https://covers.openlibrary.org/b/isbn/9781607747307-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('Spark Joy', 'Marie Kondo', 'https://covers.openlibrary.org/b/isbn/9781607749721-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('Minimalism', 'Joshua Fields Millburn', 'https://covers.openlibrary.org/b/isbn/9780143130447-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('Everything That Remains', 'Joshua Fields Millburn', 'https://covers.openlibrary.org/b/isbn/9781938793052-L.jpg', 'Self-Help', 'en', 'book', NULL, 12, NOW()),
('The More of Less', 'Joshua Becker', 'https://covers.openlibrary.org/b/isbn/9780718037134-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('Love Does', 'Bob Goff', 'https://covers.openlibrary.org/b/isbn/9780718037134-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('Everybody Always', 'Bob Goff', 'https://covers.openlibrary.org/b/isbn/9780718078731-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW()),
('Dream Big', 'Bob Goff', 'https://covers.openlibrary.org/b/isbn/9780718078731-L.jpg', 'Self-Help', 'en', 'book', NULL, 13, NOW());

-- Now insert summaries with proper UUID references using a CTE
WITH inserted_books AS (
  SELECT id, title FROM public.books 
  WHERE title IN (
    'Atomic Habits', 'The Lean Startup', 'Zero to One', 'Good to Great', 'Start With Why', 'The 4-Hour Work Week', 'The Innovator''s Dilemma', 'Blue Ocean Strategy', 'The E-Myth Revisited', 'Scaling Up', 'The Hard Thing About Hard Things', 'Daring Greatly', 'Extreme Ownership', 'Leaders Eat Last', 'The 7 Habits of Highly Effective People', 'Deep Work', 'Essentialism', 'Getting Things Done', 'The ONE Thing', 'Indistractable',
    'Thinking, Fast and Slow', 'Mindset', 'Grit', 'Emotional Intelligence', 'Flow', 'The Power of Now', 'Man''s Search for Meaning', 'The Subtle Art of Not Giving a F*ck', 'The Gifts of Imperfection', 'Untamed', 'Educated', 'Becoming', 'You Are a Badass', 'The Magic of Thinking Big', 'How to Win Friends and Influence People', 'Think and Grow Rich',
    'Rich Dad Poor Dad', 'The Intelligent Investor', 'The Little Book of Common Sense Investing', 'A Random Walk Down Wall Street', 'The Psychology of Money', 'I Will Teach You to Be Rich', 'The Simple Path to Wealth', 'Your Money or Your Life', 'The Millionaire Next Door', 'The Total Money Makeover',
    'Sapiens', 'A Brief History of Time', 'The Selfish Gene', 'Cosmos', 'The Origin of Species', 'A Short History of Nearly Everything', 'The Elegant Universe', 'The Gene', 'The Body', 'Astrophysics for People in a Hurry',
    'Meditations', 'The Art of War', 'The Republic', 'Nicomachean Ethics', 'Beyond Good and Evil', 'The Stranger', 'Existentialism is a Humanism', 'The Consolations of Philosophy', 'How to Live', 'When Breath Becomes Air',
    'Outliers', 'The Tipping Point', 'Blink', 'David and Goliath', 'The Alchemist', 'The Five Love Languages', 'The Purpose Driven Life', 'The Four Agreements', 'The Secret', 'The Power of Habit', 'Quiet', 'Predictably Irrational', 'Influence', 'The Willpower Instinct', 'Stumbling on Happiness', 'Switch', 'Nudge', 'The Paradox of Choice', 'Drive', 'The War of Art', 'Big Magic', 'Rising Strong', 'Braving the Wilderness', 'Dare to Lead', 'The Compound Effect', 'The Miracle Morning', 'High Performance Habits', 'The 5 AM Club', 'Finish', 'The 80/20 Principle', 'The Power of Full Engagement', 'The Upside of Stress', 'The Happiness Project', 'Better Than Before', 'The Four Tendencies', 'Outer Order, Inner Calm', 'The Life-Changing Magic of Tidying Up', 'Spark Joy', 'Minimalism', 'Everything That Remains', 'The More of Less', 'Love Does', 'Everybody Always', 'Dream Big'
  )
)
INSERT INTO public.summaries (book_id, short_summary, long_summary, key_insights, audio_url, created_at) VALUES
((SELECT id FROM inserted_books WHERE title = 'Atomic Habits'), 'Build tiny habits that compound into remarkable results', 'Atomic Habits by James Clear presents a comprehensive framework for building good habits and breaking bad ones. The core premise is that massive change comes from tiny, consistent actions rather than dramatic overhauls. Clear introduces the concept of "atomic habits" - small habits that compound over time to produce remarkable results. He outlines a four-step model for habit formation: cue, craving, response, and reward. The book provides practical strategies for each step: make it obvious (cue), make it attractive (craving), make it easy (response), and make it satisfying (reward). Clear emphasizes the importance of identity-based habits - becoming the type of person who embodies the desired behavior rather than just focusing on outcomes. He also discusses habit stacking, environment design, and the two-minute rule for starting new habits. The book is filled with scientific research and real-world examples that make the concepts accessible and actionable. Clear''s approach is both practical and inspiring, showing how small changes can lead to extraordinary results over time.', ARRAY['Habits are the compound interest of self-improvement - small changes compound into remarkable results', 'Focus on identity change rather than outcome-based goals to create lasting habits', 'Make good habits obvious, attractive, easy, and satisfying to ensure they stick', 'Use habit stacking to link new behaviors to existing routines', 'Environment design is crucial - make good choices easy and bad choices difficult'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The Lean Startup'), 'Learn fast by building and measuring', 'The Lean Startup by Eric Ries revolutionizes how we think about building new businesses. Ries argues that startups exist not just to make stuff, make money, or serve customers, but to learn how to build a sustainable business. The core methodology is the Build-Measure-Learn feedback loop, which emphasizes rapid experimentation and validated learning over elaborate planning. Ries introduces concepts like Minimum Viable Product (MVP), pivot or persevere decisions, and innovation accounting. He argues that failure is a necessary part of the learning process and that startups should embrace "validated learning" through continuous testing and iteration. The book provides a scientific approach to entrepreneurship that reduces waste and increases the chances of success. Ries draws on his experience as a startup founder and advisor to illustrate how companies can achieve success by being more agile, data-driven, and customer-focused. The methodology has been adopted by startups and large corporations alike as a way to innovate more effectively.', ARRAY['Startups exist to learn how to build a sustainable business model', 'Use the Build-Measure-Learn feedback loop to validate assumptions quickly', 'Minimum Viable Products help test hypotheses with minimum resources', 'Pivot when necessary based on validated learning from customer feedback', 'Innovation accounting helps measure progress and make data-driven decisions'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Zero to One'), 'Create something entirely new, not copy', 'Zero to One by Peter Thiel presents a contrarian view on innovation and entrepreneurship. Thiel argues that the most valuable companies create something entirely new (going from 0 to 1) rather than copying what already exists (going from 1 to n). He shares insights from his experience as co-founder of PayPal and early investor in Facebook, arguing that successful startups have unique insights that others miss. Thiel introduces the concept of "definite optimism" - believing in a specific vision for the future and working to create it. He discusses the importance of monopoly power, network effects, and proprietary technology in building lasting businesses. The book covers topics from technology and globalization to the future of humanity, always challenging conventional wisdom. Thiel''s contrarian thinking extends to his advice on hiring, company culture, and even the meaning of life. He argues that the best way to predict the future is to create it yourself.', ARRAY['True innovation creates something entirely new (0 to 1) rather than copying existing models', 'Monopolies are good for innovation - they have the freedom to think long-term', 'Definite optimism - believe in a specific future and work to create it', 'Competition is for losers - focus on creating unique value instead', 'Secrets are the key to breakthrough thinking - look for truths others haven''t discovered'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Good to Great'), 'Find what makes companies great', 'Good to Great by Jim Collins explores why some companies make the leap from good to great while others don''t. Collins and his research team spent five years analyzing data to identify companies that sustained exceptional performance over 15+ years. They discovered that greatness isn''t about luck or charismatic leadership, but about disciplined people, disciplined thought, and disciplined action. The book introduces several key concepts: Level 5 Leadership (humble yet driven leaders), First Who Then What (getting the right people on the bus before deciding where to go), The Hedgehog Concept (finding the intersection of passion, what you can be best at, and what drives your economic engine), and the Flywheel Effect (small consistent efforts that build momentum). Collins also discusses the importance of confronting brutal facts while maintaining faith in eventual success. The book provides a framework that applies not just to business but to any organization seeking sustained excellence.', ARRAY['Level 5 Leaders combine personal humility with intense professional will', 'Get the right people on the bus before deciding where to drive it', 'Great companies focus on their Hedgehog Concept - what they can be best at', 'Success comes from consistent effort in the right direction (Flywheel Effect)', 'Confront the brutal facts of reality while maintaining unwavering faith'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Start With Why'), 'Start with purpose to inspire action', 'Start With Why by Simon Sinek explores the fundamental question of why some organizations and leaders are more innovative, influential, and profitable than others. Sinek introduces the Golden Circle model, which consists of three concentric circles: Why (the core purpose), How (the process), and What (the result). He argues that most organizations communicate from the outside in (What-How-Why), but inspiring leaders communicate from the inside out (Why-How-What). This approach appeals to the emotional part of the brain first, building loyalty and trust. Sinek uses examples from Apple, Martin Luther King Jr., and the Wright brothers to illustrate how starting with Why creates movements rather than just customers. The book explains how this principle applies to leadership, company culture, marketing, and personal fulfillment. Sinek shows that when people share your Why, they''ll work with blood, sweat, and tears, not just for money.', ARRAY['Inspiring leaders communicate from Why to How to What, not the reverse', 'People don''t buy What you do, they buy why you do it', 'The limbic brain controls feelings and decision-making, not language', 'Starting with Why creates loyalty and trust beyond rational transactions', 'Your Why should remain constant while your How and What can evolve'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The 4-Hour Work Week'), 'Design your ideal lifestyle', 'The 4-Hour Workweek by Tim Ferriss challenges traditional notions of work and retirement. Ferriss argues that the "deferred life plan" of working hard for 40 years to enjoy retirement is outdated. Instead, he proposes a new approach: design your lifestyle to maximize freedom and minimize work time. The book introduces the DEAL framework: Definition (eliminate outdated concepts), Elimination (focus only on high-value activities), Automation (build systems that run themselves), and Liberation (free yourself from geographical constraints). Ferriss shares practical strategies for outsourcing, virtual assistants, automated income streams, and lifestyle design. He emphasizes the importance of "mini-retirements" throughout life rather than waiting until old age. The book is filled with specific tools, websites, and resources for implementing these ideas. While controversial, it has influenced millions to reconsider their relationship with work and time.', ARRAY['Focus on effectiveness (doing the right things) rather than efficiency', 'Use Parkinson''s Law to your advantage - work expands to fill available time', 'Outsource everything that doesn''t require your unique skills', 'Create automated income streams that don''t require your constant presence', 'Take mini-retirements throughout life instead of waiting for traditional retirement'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Thinking, Fast and Slow'), 'Understand your two thinking systems', 'Thinking, Fast and Slow by Nobel laureate Daniel Kahneman explores the two systems that drive how we think: System 1 (fast, intuitive, emotional) and System 2 (slow, deliberate, logical). Kahneman shows that while System 1 is essential for everyday functioning, it''s also prone to systematic errors and biases. The book reveals how these two systems interact and often conflict, leading to poor decisions. Kahneman introduces concepts like cognitive ease, anchoring, availability heuristics, and loss aversion. He demonstrates how overconfidence can affect professional judgments and how framing influences choices. The book also explores the concept of "experienced self" versus "remembering self" and how this affects our life satisfaction. Through decades of research, Kahneman provides insights into why we make the decisions we do and how we can make better ones by recognizing and compensating for our cognitive biases.', ARRAY['System 1 thinking is fast and intuitive but prone to systematic errors', 'System 2 thinking is slow and deliberate but requires mental energy', 'Cognitive biases affect even experts and professionals', 'Loss aversion makes us fear losses more than we value equivalent gains', 'Understanding these systems helps us make more rational decisions'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Mindset'), 'Develop a growth mindset for success', 'Mindset by Carol Dweck presents decades of research on how our beliefs about ability shape our success. Dweck identifies two mindsets: fixed mindset (believing abilities are static) and growth mindset (believing abilities can be developed). People with a growth mindset embrace challenges, persist through setbacks, and see effort as the path to mastery. Those with a fixed mindset avoid challenges, give up easily, and see effort as fruitless. Dweck shows how these mindsets develop in childhood and affect every area of life: academics, sports, business, and relationships. The book provides strategies for cultivating a growth mindset in ourselves and others. Dweck demonstrates that changing our mindset can transform our lives, turning obstacles into opportunities and failures into learning experiences. The research shows that even small changes in how we think about ability can have profound effects on achievement.', ARRAY['Growth mindset people see abilities as developable through effort and learning', 'Fixed mindset people believe abilities are static and fear looking incompetent', 'Praise effort and strategy rather than intelligence or talent', 'View challenges as opportunities to grow rather than threats to ego', 'The brain is like a muscle - it grows stronger with exercise and learning'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Grit'), 'Develop passion and perseverance for achievement', 'Grit by Angela Duckworth argues that the secret to outstanding achievement is not talent but a special blend of passion and persistence she calls "grit." Duckworth, a psychologist and MacArthur Fellow, shows that grit is a better predictor of success than IQ, talent, or luck. She defines grit as having four components: interest, practice, purpose, and hope. The book explores how gritty people pursue long-term goals with passion and perseverance, bouncing back from setbacks and staying the course. Duckworth shares stories from West Point cadets, National Spelling Bee champions, and successful business leaders to illustrate grit in action. She also provides practical strategies for cultivating grit in ourselves and others. The book challenges the "natural talent" myth and shows that effort counts twice in the achievement equation. Duckworth''s research suggests that anyone can develop grit through deliberate practice and finding purpose in their pursuits.', ARRAY['Grit equals passion plus perseverance for long-term goals', 'Effort counts twice: it builds skill and makes skill productive', 'Deliberate practice - focused, goal-oriented effort - builds expertise', 'Hope is essential - believing tomorrow can be better than today', 'Cultivate interest, practice, purpose, and hope to develop grit'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Emotional Intelligence'), 'Recognize and manage emotions effectively', 'Emotional Intelligence by Daniel Goleman revolutionized our understanding of what it means to be smart. Goleman argues that EI - the ability to recognize, understand, and manage our own emotions and those of others - is more important than IQ for success in life. The book breaks EI into five components: self-awareness, self-regulation, motivation, empathy, and social skills. Goleman shows how these skills affect relationships, leadership, health, and decision-making. He demonstrates that emotions are not the enemy of reason but essential to effective thinking and action. The book draws on neuroscience and psychology to explain how the brain processes emotions and how we can develop better emotional habits. Goleman provides practical strategies for improving each aspect of emotional intelligence. The research shows that people with high EI tend to be more successful leaders, have better relationships, and enjoy better health outcomes.', ARRAY['Emotional intelligence can be more important than IQ for life success', 'Self-awareness is the foundation - recognize your emotions as they happen', 'Self-regulation involves managing impulses and thinking before acting', 'Empathy allows you to understand others'' emotions and perspectives', 'Social skills combine emotional awareness with effective communication'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Flow'), 'Achieve optimal experience through focus', 'Flow by Mihaly Csikszentmihalyi explores the state of optimal experience he calls "flow" - those moments when we''re so absorbed in an activity that time seems to disappear. Csikszentmihalyi, a pioneering psychologist, shows that flow occurs when there''s a perfect balance between challenge and skill. The book explains the characteristics of flow: clear goals, immediate feedback, deep concentration, and a sense of control. Flow experiences lead to personal growth, creativity, and life satisfaction. Csikszentmihalyi shows how to create more flow in work, relationships, and daily life. He argues that happiness isn''t something that happens to us but something we can cultivate by structuring our lives to create flow experiences. The book provides a scientific understanding of enjoyment and practical guidance for living a more engaging and fulfilling life. Flow represents a revolutionary approach to psychology that focuses on positive experiences rather than pathology.', ARRAY['Flow occurs when challenge and skill are perfectly balanced', 'Clear goals and immediate feedback are essential for flow states', 'Flow leads to personal growth and increased life satisfaction', 'Structure your life to create more flow experiences', 'The quality of experience matters more than the quantity of pleasure'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The Power of Now'), 'Live in present moment', 'The Power of Now by Eckhart Tolle presents a spiritual guide to living in the present moment. Tolle argues that most human suffering comes from being trapped in past regrets or future anxieties rather than experiencing the present. He introduces the concept of the "pain-body" - accumulated emotional pain that feeds on negative thoughts. The book teaches how to disidentify from the thinking mind and connect with deeper consciousness. Tolle explains that the present moment is all we ever have and that true peace and enlightenment come from embracing it. He provides practical techniques for staying present, including observing your thoughts without judgment and focusing on inner body sensations. The book has helped millions find relief from anxiety, depression, and stress by learning to live more fully in the now. Tolle''s message is both simple and profound: the key to spiritual awakening is to realize that you are not your thoughts but the awareness behind them.', ARRAY['The present moment is the only time that truly exists', 'Most suffering comes from psychological time - past and future thinking', 'You are not your thoughts but the awareness that observes thoughts', 'The pain-body feeds on negative emotions and resistance to the present', 'True freedom comes from accepting the present moment as it is'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Man''s Search for Meaning'), 'Find meaning in any circumstance', 'Man''s Search for Meaning by Viktor Frankl is a profound meditation on finding meaning in suffering. Frankl, a psychiatrist and Holocaust survivor, describes his experiences in Nazi concentration camps and how he found meaning even in the most horrific circumstances. He argues that humans'' primary drive is not pleasure but the pursuit of meaning. Frankl developed logotherapy, which helps people discover their purpose in life. The book is divided into two parts: his camp experiences and an explanation of logotherapy. Frankl shows that even when everything is taken away, humans still retain the freedom to choose their attitude. He demonstrates how meaning can be found through work, love, and courage in the face of suffering. The book has inspired millions with its message that meaning can be found in any circumstance. Frankl''s insights come from both his professional expertise and his personal experience of extreme suffering.', ARRAY['The primary human drive is the will to meaning, not pleasure', 'Even in suffering, we retain the freedom to choose our attitude', 'Meaning can be found through work, love, and courage in adversity', 'Those who have a "why" to live can bear almost any "how"', 'Logotherapy helps people discover their unique purpose in life'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Rich Dad Poor Dad'), 'Think differently about money', 'Rich Dad Poor Dad by Robert Kiyosaki challenges conventional financial wisdom through the story of his two fathers: his highly educated but poor biological father, and his best friend''s entrepreneurial and wealthy father. Kiyosaki contrasts their different approaches to money, showing how the rich think differently about assets, liabilities, and financial education. The book emphasizes the importance of financial literacy over academic achievement. Kiyosaki introduces concepts like the cashflow quadrant, the difference between assets and liabilities, and the power of passive income. He argues that the middle class works for money while the rich have money work for them. The book encourages readers to build businesses and invest in assets that generate cash flow. While controversial, it has inspired millions to take control of their financial education and pursue financial independence through entrepreneurship and investing.', ARRAY['Assets put money in your pocket, liabilities take money out', 'The rich buy or create assets, middle class buy liabilities', 'Financial education is more important than academic education', 'Work to learn, not just to earn - acquire skills that build wealth', 'Mind your own business - build a system that works without you'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Sapiens'), 'Learn human history from cognitive revolution', 'Sapiens by Yuval Noah Harari is a sweeping history of humankind from the Stone Age to the present. Harari explores how Homo sapiens came to dominate the planet through unique cognitive abilities. He argues that the key to human success was the ability to create and believe in shared fictions - things like gods, nations, money, and human rights that exist only in our collective imagination. The book covers three major revolutions: Cognitive Revolution (70,000 years ago), Agricultural Revolution (12,000 years ago), and Scientific Revolution (500 years ago). Harari examines how these revolutions transformed human society, for better and worse. He also speculates about the future of humanity, including the possibility of genetic engineering and artificial intelligence. The book challenges readers to question fundamental assumptions about human nature, progress, and the meaning of life. Sapiens has become a global phenomenon for its accessible yet profound exploration of human history.', ARRAY['Shared fictions (gods, nations, money) enabled large-scale human cooperation', 'The Agricultural Revolution was history''s biggest fraud - humans worked harder for worse nutrition', 'Money is the most successful story ever told - everyone believes in it', 'Science and capitalism are interdependent systems driving modern progress', 'The future of humanity may involve genetic engineering and artificial intelligence'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Deep Work'), 'Focus deeply for better results', 'Deep Work by Cal Newport argues that the ability to focus without distraction on cognitively demanding tasks is becoming increasingly rare and valuable. Newport defines deep work as professional activities performed in a state of distraction-free concentration that push cognitive capabilities to their limit. He contrasts this with shallow work - non-cognitively demanding tasks that can be performed while distracted. The book shows how deep work produces better results in less time and is essential for mastering difficult skills. Newport provides strategies for cultivating deep work: embracing boredom, scheduling deep work sessions, and creating distraction-free environments. He also explains how to measure the value of your work and say no to shallow commitments. Newport argues that deep work is becoming more valuable as automation handles routine tasks, making it the key to career success and personal fulfillment. The book is both a manifesto for focused work and a practical guide to achieving it.', ARRAY['Deep work produces exponentially better results than shallow work', 'The ability to focus deeply is becoming increasingly rare and valuable', 'Schedule deep work sessions like appointments and protect them rigorously', 'Embrace boredom to train your brain to resist distraction', 'Measure your work by depth of focus, not hours spent'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The 7 Habits of Highly Effective People'), 'Build effective habits for success', 'The 7 Habits of Highly Effective People by Stephen Covey presents a holistic approach to personal and professional effectiveness. Covey argues that true effectiveness requires character development, not just quick fixes. The habits are organized into three categories: Private Victory (habits 1-3), Public Victory (habits 4-6), and Renewal (habit 7). The habits are: Be Proactive, Begin with the End in Mind, Put First Things First, Think Win-Win, Seek First to Understand Then to Be Understood, Synergize, and Sharpen the Saw. Covey emphasizes that these habits are based on principles that are timeless and universal. He shows how the habits build on each other, creating a foundation for lasting effectiveness. The book has influenced millions with its principle-centered approach to personal development. Covey''s framework provides a comprehensive guide for living a more effective, principle-driven life.', ARRAY['Be proactive - take responsibility for your choices and responses', 'Begin with the end in mind - visualize your destination before starting', 'Put first things first - prioritize important over urgent activities', 'Think win-win - seek mutual benefit in all interactions', 'Seek first to understand, then to be understood - listen before speaking'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Essentialism'), 'Do less but achieve more', 'Essentialism by Greg McKeown presents a systematic discipline for discerning what is absolutely essential and eliminating everything else. McKeown argues that the way to get more done is not to do more but to do less - only what truly matters. He introduces the concept of the "essentialist" who deliberately chooses where to invest their time and energy. The book provides a framework for identifying what''s essential: explore more, sleep on decisions, apply extreme criteria, and say no gracefully. McKeown shows how essentialism applies to work, relationships, and personal life. He emphasizes that essentialism isn''t about doing less for the sake of less, but about doing only the right things. The book helps readers overcome the "undisciplined pursuit of more" that leads to burnout and mediocrity. Essentialism provides a path to greater focus, clarity, and effectiveness.', ARRAY['If you don''t prioritize your life, someone else will', 'Trade-offs are inevitable - choose what to give up rather than trying to have it all', 'Apply extreme criteria - is this absolutely essential?', 'Protect the asset - your health and energy are essential for effectiveness', 'Say no gracefully but firmly to non-essential commitments'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The Psychology of Money'), 'Understand financial behavior', 'The Psychology of Money by Morgan Housel explores the strange ways people think about money and how to make better financial decisions. Housel argues that financial success isn''t about intelligence but about behavior and psychology. He shares 19 short stories that illustrate key insights about money, investing, and wealth. The book shows how luck, risk, and time play crucial roles in financial outcomes. Housel emphasizes that there''s no "right" way to handle money - what works for one person may not work for another. He discusses concepts like the difference between being rich and being wealthy, the power of compounding, and the importance of saving rate over investment returns. Housel''s writing is accessible and filled with memorable anecdotes that make complex financial concepts easy to understand. The book helps readers develop a healthier relationship with money and make better financial decisions.', ARRAY['Your personal experiences with money shape your financial behavior more than education', 'Wealth is what you don''t see - savings not spent', 'Compounding is more powerful than you think, given enough time', 'Luck and risk play huge roles in financial outcomes', 'The best financial plan is to save aggressively and invest for the long term'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'Outliers'), 'Success depends on hidden advantages', 'Outliers by Malcolm Gladwell challenges the myth of the "self-made" person by examining the factors that contribute to extraordinary success. Gladwell argues that success is not just about individual merit but about opportunity, timing, and cultural background. He introduces the "10,000-hour rule" - the idea that mastery requires approximately 10,000 hours of deliberate practice. The book explores how factors like birth month, family background, and cultural legacy affect achievement. Gladwell uses examples from hockey players, software programmers, and pilots to illustrate how hidden advantages shape success. He also examines how cultural differences can lead to plane crashes and communication breakdowns. Outliers shows that success is the product of many factors coming together at the right time. The book encourages readers to look beyond individual talent and consider the broader context of achievement.', ARRAY['Success depends on opportunity as much as individual merit', 'The 10,000-hour rule - mastery requires extensive deliberate practice', 'Cultural background and timing play crucial roles in achievement', 'Hidden advantages can make the difference between success and failure', 'Success is the product of many factors, not just individual talent'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The Alchemist'), 'Follow your personal legend', 'The Alchemist by Paulo Coelho is a philosophical novel about following your dreams and listening to your heart. The story follows Santiago, a shepherd boy who sells his flock to pursue a treasure he dreams of finding near the Egyptian pyramids. Along his journey, Santiago meets various characters who teach him about the "Soul of the World" and the importance of following one''s "Personal Legend." The book explores themes of destiny, love, and the interconnectedness of all things. Coelho uses simple language to convey profound spiritual truths about the journey of self-discovery. The novel suggests that when you want something, the entire universe conspires to help you achieve it. The Alchemist has inspired millions with its message that the journey is as important as the destination and that the true treasure lies within. The book combines storytelling with spiritual wisdom in a way that resonates across cultures.', ARRAY['Follow your Personal Legend - your unique path in life', 'When you want something, the universe conspires to help you achieve it', 'The journey itself contains the treasure you seek', 'Learn to read omens and listen to your heart', 'Fear is the greatest obstacle to pursuing your dreams'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'How to Win Friends and Influence People'), 'Build better relationships', 'How to Win Friends and Influence People by Dale Carnegie is a classic guide to human relations and social skills. First published in 1936, the book presents fundamental principles for dealing with people effectively. Carnegie''s advice is based on the idea that you can get what you want by making other people want what you want. The book is divided into sections: fundamental techniques in handling people, ways to make people like you, how to win people to your way of thinking, and how to be a leader. Carnegie''s principles include becoming genuinely interested in other people, remembering names, listening more than talking, and avoiding criticism. He emphasizes the importance of appreciation, encouragement, and making others feel important. The book''s timeless wisdom comes from understanding human psychology and the universal desire for recognition and respect. Despite being written decades ago, the principles remain relevant in our digital age.', ARRAY['Become genuinely interested in other people rather than trying to get them interested in you', 'Remember that a person''s name is the sweetest sound in any language', 'Listen more than you talk and encourage others to talk about themselves', 'Avoid criticism, condemnation, and complaint - they create resentment', 'Make the other person feel important and do it sincerely'], NULL, NOW()),

((SELECT id FROM inserted_books WHERE title = 'The Art of War'), 'Win without fighting through strategy', 'The Art of War by Sun Tzu is an ancient Chinese treatise on military strategy that has become a classic guide for conflict resolution and strategic thinking. Written over 2,500 years ago, the book presents principles that apply to business, politics, and personal relationships as well as warfare. Sun Tzu emphasizes the importance of knowing yourself and your enemy, understanding terrain, and using deception. He advocates winning without fighting through superior strategy and positioning. The book is divided into 13 chapters covering topics like laying plans, waging war, attack by stratagem, and use of spies. Sun Tzu''s philosophy emphasizes flexibility, adaptation, and the importance of avoiding direct conflict when possible. The Art of War teaches that the supreme art of war is to subdue the enemy without fighting. Its timeless principles have influenced leaders across cultures and centuries.', ARRAY['Know yourself and know your enemy - you will never be in peril', 'All warfare is based on deception - appear weak when strong, strong when weak', 'The supreme art of war is to subdue the enemy without fighting', 'Opportunities multiply as they are seized', 'In the midst of chaos, there is also opportunity'], NULL, NOW());
